name: auto-version

on:

  push:
    branches: [ main ]    
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Reset Origin
        run: |
          git remote set-url origin "https://cdavernas:${{ secrets.GITHUB_TOKEN }}@github.com/serverlessworkflow/synapse.git"
          git checkout ${{ github.ref_name }}
          
      - name: Install Versioning.NET
        run: |
          dotnet tool install --global Versioning.NET
          
      - name: Increment Version
        run: |
          dotnet-version increment-version-with-git -g "." --branch-name ${{ github.ref_name }} --author-email actions@github.com
