
name: "PublishPlugins"

on:
  push:
    branches: [ main ]
    
jobs:
  release-eventstore-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="EventStoreRepositoryPlugin"
          # Publish
          dotnet publish src/plugins/persistence/Synapse.Plugins.Persistence.EventStore/Synapse.Plugins.Persistence.EventStore.csproj -c Release -o "${release_name}"
          # Pack
          tar czvf "${release_name}.tar.gz" "${release_name}"
          # Delete output directory
          rm -r "${release_name}"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.1.2
          files: "EventStoreRepositoryPlugin*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  release-mongodb-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="MongoDBRepositoryPlugin"
          # Publish
          dotnet publish src/plugins/persistence/Synapse.Plugins.Persistence.MongoDB/Synapse.Plugins.Persistence.MongoDB.csproj -c Release -o "${release_name}"
          # Pack
          tar czvf "${release_name}.tar.gz" "${release_name}"
          # Delete output directory
          rm -r "${release_name}"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.1.2
          files: "MongoDBRepositoryPlugin*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
